# Generated by Django 6.0.6 on 2026-06-13 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='segment_city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
